HW9/CS460_Hwk08/Models/Athlete.cs
namespace CS460_Hwk08.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Athlete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Athlete()
        {
            RaceResults = new HashSet<RaceResult>();
        }

        //===============================================================================
        public int AthleteID { get; set; }

        //-------------------------------------------------------------------------------
        [Required, DisplayName("athlete")]
        [StringLength(72)]
        public string AthleteName { get; set; }

        //-------------------------------------------------------------------------------
        [Required, DisplayName("gender")]
        [StringLength(6)]
        public string Gender { get; set; }

        //-------------------------------------------------------------------------------
        public int CoachID { get; set; }

        //-------------------------------------------------------------------------------
        public int TeamID { get; set; }

        //-------------------------------------------------------------------------------
        [DisplayName("coach")]
        public virtual Coach Coach { get; set; }

        //-------------------------------------------------------------------------------
        [DisplayName("team")]
        public virtual Team Team { get; set; }

        //===============================================================================
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceResult> RaceResults { get; set; }

        //===============================================================================
    }
}

HW9/CS460_Hwk08/Controllers/RaceResultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CS460_Hwk08.DAL;      
using CS460_Hwk08.Models;
using CS460_Hwk08.Models.ViewModels;

namespace CS460_Hwk08.Controllers
{
    public class RaceResultsController : Controller
    {
        // we pull in the db through our context class -- like w/Hwk_05 & _06
        private TrackContext db = new TrackContext();

        //===============================================================================
        // GET: RaceResults
        [HttpGet]
        public ActionResult Index()
        {
            // added ordering by meet date
            var raceResults = db.RaceResults.Include(r => r.Athlete)
                                            .Include(r => r.Coach)
                                            .Include(r => r.Event)
                                            .Include(r => r.Location)
                                            .Include(r => r.Team)
                                            .OrderBy(r => r.MeetDate);

            return View(raceResults.ToList());
            // so why does *THIS* 'ToList()' work?????
            // and mine does not in 'ResultsList'?????
            // why no 'IEnumerable' error on this?????
            //
            // and where is '.Include(r => r.MeetDate) up there???  it's in the View.....
            // and where is '.Include( => r.FinishTime)?   oooooh.... okay -- it's only
            //                                             doing the non-native ones.....
            // learn more about '.Include()':
            // https://docs.microsoft.com/en-us/dotnet/api/system.data.objects.objectquery-1.include?view=netframework-4.8
        }
        //===============================================================================
        // GET: RaceResults/Details/5
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            RaceResult raceResult = db.RaceResults.Find(id);
            if (raceResult == null)
            {
                return HttpNotFound();
            }

            return View(raceResult);
        }

        //===============================================================================
        // GET: RaceResults/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.AthleteID = new SelectList(db.Athletes.OrderBy(a => a.AthleteName), "AthleteID", "AthleteName");
            ViewBag.CoachID = new SelectList(db.Coaches.OrderBy(c => c.CoachName), "CoachID", "CoachName");
            ViewBag.EventID = new SelectList(db.Events.OrderBy(e => e.EventType), "EventID", "EventType");
            ViewBag.LocationID = new SelectList(db.Locations.OrderBy(l => l.LocationName), "LocationID", "LocationName");
            ViewBag.TeamID = new SelectList(db.Teams.OrderBy(t => t.TeamName), "TeamID", "TeamName");
            ViewBag.GenderList = genderSelectList;

            return View();
        }

        //-------------------------------------------------------------------------------
        // POST: RaceResults/Create
        // To protect from overposting attacks, 
        // please enable the specific properties you want to bind to, 
        // for more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RaceResultID,LocationID,MeetDate,Gender,FinishTime,AthleteID,CoachID,TeamID,EventID")] RaceResult raceResult)
        {
            if (ModelState.IsValid)
            {
                db.RaceResults.Add(raceResult);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AthleteID = new SelectList(db.Athletes.OrderBy(a => a.AthleteName), "AthleteID", "AthleteName", raceResult.AthleteID);
            ViewBag.CoachID = new SelectList(db.Coaches.OrderBy(c => c.CoachName), "CoachID", "CoachName", raceResult.CoachID);
            ViewBag.EventID = new SelectList(db.Events.OrderBy(e => e.EventType), "EventID", "EventType", raceResult.EventID);
            ViewBag.LocationID = new SelectList(db.Locations.OrderBy(l => l.LocationName), "LocationID", "LocationName", raceResult.LocationID);
            ViewBag.TeamID = new SelectList(db.Teams.OrderBy(t => t.TeamName), "TeamID", "TeamName", raceResult.TeamID);

            return View(raceResult);
        }

        //===============================================================================
        // GET: RaceResults/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RaceResult raceResult = db.RaceResults.Find(id);
            if (raceResult == null)
            {
                return HttpNotFound();
            }

            ViewBag.AthleteID = new SelectList(db.Athletes.OrderBy(a => a.AthleteName), "AthleteID", "AthleteName", raceResult.AthleteID);
            ViewBag.CoachID = new SelectList(db.Coaches.OrderBy(c => c.CoachName), "CoachID", "CoachName", raceResult.CoachID);
            ViewBag.EventID = new SelectList(db.Events.OrderBy(e => e.EventType), "EventID", "EventType", raceResult.EventID);
            ViewBag.LocationID = new SelectList(db.Locations.OrderBy(l => l.LocationName), "LocationID", "LocationName", raceResult.LocationID);
            ViewBag.TeamID = new SelectList(db.Teams.OrderBy(t => t.TeamName), "TeamID", "TeamName", raceResult.TeamID);
            ViewBag.GenderList = genderSelectList;

            return View(raceResult);
        }

        //-------------------------------------------------------------------------------
        // POST: RaceResults/Edit/5
        // To protect from overposting attacks, 
        // please enable the specific properties you want to bind to, 
        // for more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RaceResultID,LocationID,MeetDate,Gender,FinishTime,AthleteID,CoachID,TeamID,EventID")] RaceResult raceResult)
        {
            if (ModelState.IsValid)
            {
                db.Entry(raceResult).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AthleteID = new SelectList(db.Athletes.OrderBy(a => a.AthleteName), "AthleteID", "AthleteName", raceResult.AthleteID);
            ViewBag.CoachID = new SelectList(db.Coaches.OrderBy(c => c.CoachName), "CoachID", "CoachName", raceResult.CoachID);
            ViewBag.EventID = new SelectList(db.Events.OrderBy(e => e.EventType), "EventID", "EventType", raceResult.EventID);
            ViewBag.LocationID = new SelectList(db.Locations.OrderBy(l => l.LocationName), "LocationID", "LocationName", raceResult.LocationID);
            ViewBag.TeamID = new SelectList(db.Teams.OrderBy(t => t.TeamName), "TeamID", "TeamName", raceResult.TeamID);

            return View(raceResult);
        }

        //===============================================================================
        // GET: RaceResults/Delete/5
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RaceResult raceResult = db.RaceResults.Find(id);
            if (raceResult == null)
            {
                return HttpNotFound();
            }

            return View(raceResult);
        }

        //-------------------------------------------------------------------------------
        // POST: RaceResults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RaceResult raceResult = db.RaceResults.Find(id);
            db.RaceResults.Remove(raceResult);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //===============================================================================
        //===============================================================================
        //-------- BOY/GIRL DROP-DOWN LIST IN 'CREATE (and edit) RACE RESULT' -----------
        //
        private IList<SelectListItem> genderSelectList = new List<SelectListItem>
        {
            new SelectListItem
                { Value = "girls", Text="girls" },
            new SelectListItem
                { Value = "boys", Text="boys" },
        };
        //===============================================================================
        //===============================================================================
        // GET: page that shows table of all results for an athlete => part of Feature#2
        [HttpGet]
        public ActionResult Results()
        {
            // this makes the drop-down list from which to choose an athlete.....
            ViewBag.AthleteID = new SelectList(db.Athletes, "AthleteID", "AthleteName");

            return View();
        }
        //===============================================================================
        [HttpPost]
        public ActionResult ResultsList(int AthleteID)
        {
            // so..... based off Hwk06 & the Search Box Feature..... 
            //   we pass in that up there, from the name of the drop-down in the View...

HW9/CS460_Hwk08/Views/Athletes/Create.cshtml
@model CS460_Hwk08.Models.Athlete

@{
    ViewBag.Title = "add a new athlete";
}

<h2>add a new athlete</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
<!-------------------------------------------------------------------------------------->
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!------------------------------------------------------------------------------>
        <div class="form-group">
            @Html.LabelFor(model => model.AthleteName, 
                               htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.AthleteName, new { htmlAttributes = 
                new { @class = "form-control", placeholder = "athlete name", required = "required" } })

                @Html.ValidationMessageFor(model => model.AthleteName, "", 
                                                          new { @class = "text-danger" })
            </div>
        </div>

        <!------------------------------------------------------------------------------>
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, 
                               htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownList("gender",
                    (IEnumerable<SelectListItem>)ViewBag.GenderList,
                        "gender?", new { @class = "form-control", required = "required" })

                @Html.ValidationMessageFor(model => model.Gender, "", 
                                                        new { @class = "text-danger" })
            </div>
        </div>

        <!------------------------------------------------------------------------------>
        <div class="form-group">
            @Html.LabelFor(model => model.TeamID, "team", 
                               htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownList("TeamID", null, "team name", htmlAttributes: 
                new { @class = "form-control", placeholder = "team name", required = "required" })
                @Html.ValidationMessageFor(model => model.TeamID, "", 
                                                          new { @class = "text-danger" })
            </div>
        </div>

        <!------------------------------------------------------------------------------>
        <div class="form-group">
            @Html.LabelFor(model => model.CoachID, "coach", htmlAttributes: 
                                               new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownList("CoachID", null, "coach name", htmlAttributes: 
                new { @class = "form-control", placeholder = "coach name", required = "required" })
                @Html.ValidationMessageFor(model => model.CoachID, "", 
                                                          new { @class = "text-danger" })
            </div>
        </div>

        <!------------------------------------------------------------------------------>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="save" class="btn btn-default" />
            </div>
        </div>
        <!------------------------------------------------------------------------------>
    </div>
}
<!-------------------------------------------------------------------------------------->
<div>
    @Html.ActionLink("back to all athletes", "Index")
</div>
<!-------------------------------------------------------------------------------------->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<!-------------------------------------------------------------------------------------->

HW9/CS460_Hwk08/Views/Athletes/Delete.cshtml
@model CS460_Hwk08.Models.Athlete

@{
    ViewBag.Title = "delete this athlete";
}

<h2>delete this athlete</h2>

<h3>are you sure you want to delete this?</h3>
<div>
    <!---------------------------------------------------------------------------------->
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Coach.CoachName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Coach.CoachName)
        </dd>
        <!------------------------------------------------------------------------------>
        <dt>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.TeamName)
        </dd>
        <!------------------------------------------------------------------------------>
        <dt>
            @Html.DisplayNameFor(model => model.AthleteName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AthleteName)
        </dd>
        <!------------------------------------------------------------------------------>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <!------------------------------------------------------------------------------>
    </dl>
    <!---------------------------------------------------------------------------------->
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="delete" class="btn btn-default" /> |
            @Html.ActionLink("back to all athletes", "Index")
        </div>
    }
    <!---------------------------------------------------------------------------------->
</div>

HW9/CS460_Hwk08/Views/Athletes/Details.cshtml
@model CS460_Hwk08.Models.Athlete

@{
    ViewBag.Title = "athlete details";
}

<h2>athlete details</h2>

<div>
    <!---------------------------------------------------------------------------------->
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AthleteName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AthleteName)
        </dd>
        <!------------------------------------------------------------------------------>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <!------------------------------------------------------------------------------>
        <dt>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.TeamName)
        </dd>
        <!------------------------------------------------------------------------------>
        <dt>
            @Html.DisplayNameFor(model => model.Coach.CoachName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Coach.CoachName)
        </dd>
        <!------------------------------------------------------------------------------>
    </dl>
</div>
<!-------------------------------------------------------------------------------------->
<p>
    @Html.ActionLink("edit", "Edit", new { id = Model.AthleteID }) |
    @Html.ActionLink("back to all athletes", "Index")
</p>
<!-------------------------------------------------------------------------------------->

HW9/CS460_Hwk08/Views/Athletes/Edit.cshtml
@model CS460_Hwk08.Models.Athlete

@{
    ViewBag.Title = "edit this athlete";
}

<h2>edit this athlete</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <!------------------------------------------------------------------------------>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AthleteID)

        <div class="form-group">
            @Html.LabelFor(model => model.AthleteName, htmlAttributes: new { @class = "control-label col-md-2" })
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.AthleteName, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.AthleteName, "", new { @class = "text-danger" })
            </div>
        </div>

        <!------------------------------------------------------------------------------>
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })*@

                @Html.DropDownList("gender",
                (IEnumerable<SelectListItem>)ViewBag.GenderList,
                    "gender?", new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <!------------------------------------------------------------------------------>
        <div class="form-group">
            @Html.LabelFor(model => model.CoachID, "CoachID", htmlAttributes: new { @class = "control-label col-md-2" })
            
            <div class="col-md-10">
                @Html.DropDownList("CoachID", null, htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.CoachID, "", new { @class = "text-danger" })
            </div>
        </div>

        <!------------------------------------------------------------------------------>
        <div class="form-group">
            @Html.LabelFor(model => model.TeamID, "TeamID", htmlAttributes: new { @class = "control-label col-md-2" })
            
            <div class="col-md-10">
                @Html.DropDownList("TeamID", null, htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.TeamID, "", new { @class = "text-danger" })
            </div>
        </div>

        <!------------------------------------------------------------------------------>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="save" class="btn btn-default" />
            </div>
        </div>
        <!------------------------------------------------------------------------------>
    </div>
}
<!-------------------------------------------------------------------------------------->
<div>
    @Html.ActionLink("back to all athletes", "Index")
</div>
<!-------------------------------------------------------------------------------------->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<!-------------------------------------------------------------------------------------->

HW9/CS460_Hwk08/Views/Athletes/Index.cshtml
@model IEnumerable<CS460_Hwk08.Models.Athlete>

@{
    ViewBag.Title = "student athletes";
}

<h2>student athletes</h2>

<!-------------------------------------------------------------------------------------->
<div class=" btn my_add">
    <b>@Html.ActionLink("add a new athlete", "Create")</b>
</div>

<div class="btn my_add">
    <b>@Html.ActionLink("see all races for an athlete", "Results", "RaceResults")</b>
</div>

<div class="btn my_add">
    <b>@Html.ActionLink("check athlete stats", "Stats", "RaceResults")</b>
</div>

<!-------------------------------------------------------------------------------------->
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AthleteName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Coach.CoachName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </th>
        <th></th>
    </tr>
    <!---------------------------------------------------------------------------------->
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AthleteName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Team.TeamName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Coach.CoachName)
            </td>
            <!-------------------------------------------------------------------------->
            <td>
                @Html.ActionLink("details", "Details", new { id = item.AthleteID }) |
                @Html.ActionLink("edit", "Edit", new { id = item.AthleteID }) |
                @Html.ActionLink("delete", "Delete", new { id = item.AthleteID })
            </td>
        </tr>
}
</table>